name: Run Tests

on:
  pull_request:
    branches:
      - main
  push: 
    branches:
      - ${GITHUB_REF##*/}

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 16
        
    - name: Install NPM packages
      run: npm i
    
    - name: Run test script
      run: npm run test